Repository HipstuCAU/nyam_nyam, pull requests merged in 2023-03, with the labels that each got.

#7 UserDefaults Extension과 첫로딩시 기본값 설정하는 함수를 추가하였습니다.
  NyamNyam/NyamNyam.xcodeproj/project.pbxproj
  NyamNyam/NyamNyam/Global/Extension+/UserDefaults+.swift
  NyamNyam/NyamNyam/Network/Model/Campus.swift
  NyamNyam/NyamNyam/Screens/Home/Components/OptionSelectModule/CampusSelectView.swift
  NyamNyam/NyamNyam/Screens/Home/Components/OptionSelectModule/OptionSelectModuleViewController.swift
  NyamNyam/NyamNyam/Screens/Home/HomeViewController.swift
Labels: feature

#8 Campus 옵션을 고르는 영역을 만들었습니다.
  NyamNyam/NyamNyam.xcodeproj/project.pbxproj
  NyamNyam/NyamNyam/Assets.xcassets/Buttons/Contents.json
  NyamNyam/NyamNyam/Assets.xcassets/Buttons/chevron.down.imageset/Contents.json
  NyamNyam/NyamNyam/Assets.xcassets/Buttons/chevron.down.imageset/Image 1.png
  NyamNyam/NyamNyam/Assets.xcassets/Buttons/chevron.down.imageset/Image 2.png
  NyamNyam/NyamNyam/Assets.xcassets/Buttons/chevron.down.imageset/Image.png
  NyamNyam/NyamNyam/Assets.xcassets/Colors/Contents.json
  NyamNyam/NyamNyam/Assets.xcassets/Colors/blue.colorset/Contents.json
  NyamNyam/NyamNyam/Assets.xcassets/Colors/cauBlue.colorset/Contents.json
  NyamNyam/NyamNyam/Assets.xcassets/Colors/cauRed.colorset/Contents.json
  NyamNyam/NyamNyam/Assets.xcassets/Colors/gray.colorset/Contents.json
  NyamNyam/NyamNyam/Assets.xcassets/Colors/gray50.colorset/Contents.json
  NyamNyam/NyamNyam/Assets.xcassets/Colors/red.colorset/Contents.json
  NyamNyam/NyamNyam/Assets.xcassets/Colors/yellow.colorset/Contents.json
  NyamNyam/NyamNyam/Global/Pallete.swift
  NyamNyam/NyamNyam/Screens/Home/Components/OptionSelectModule/CampusSelectView.swift
  NyamNyam/NyamNyam/Screens/Home/Components/OptionSelectModule/OptionSelectModuleViewController.swift
  NyamNyam/NyamNyam/Screens/Home/HomeViewController.swift
  NyamNyam/NyamNyam/Screens/Home/HomeViewModel.swift
Labels: feature

#12 Json 구조 변경으로 인한 DummyData를 수정합니다
  NyamNyam/NyamNyam/Network/Dummy.json
Labels: documentation

#17 Meal 모델을 수정하였습니다.
  NyamNyam/NyamNyam/Network/Model/Meal.swift
Labels: refactor

#20 DataManager의 string 데이터를 dictionary로 파싱하는 함수와 데이터 정제 함수들을 구현합니다.
  NyamNyam/NyamNyam.xcodeproj/project.pbxproj
  NyamNyam/NyamNyam/Global/Manager/DataManager.swift
  NyamNyam/NyamNyam/Global/Manager/JsonManager.swift
  NyamNyam/NyamNyam/Network/Model/Meal.swift
  NyamNyam/NyamNyam/Screens/Home/Components/OptionSelectModule/CafeteriaSelectView.swift
Labels: feature

#23 버튼 초기값과 CollectionView 새로고침 오류를 수정하였습니다.
  NyamNyam/NyamNyam/Application/AppDelegate.swift
  NyamNyam/NyamNyam/Screens/Home/ContentCarouselModule/ContentCarouselModuleViewController.swift
Labels: fix

#28 Meal 모델에 파싱될 정제함수를 수정하였습니다
  NyamNyam/NyamNyam/Global/Manager/DataManager.swift
Labels: feature

#32 Expandable한 UIView클래스를 만들었습니다.
  NyamNyam/NyamNyam.xcodeproj/project.pbxproj
  NyamNyam/NyamNyam/Assets.xcassets/Buttons/menuViewButton.imageset/Contents.json
  NyamNyam/NyamNyam/Assets.xcassets/Buttons/menuViewButton.imageset/Image.png
  NyamNyam/NyamNyam/Assets.xcassets/Buttons/menuViewButton.imageset/Image@2x.png
  NyamNyam/NyamNyam/Assets.xcassets/Buttons/menuViewButton.imageset/Image@3x.png
  NyamNyam/NyamNyam/Assets.xcassets/Colors/bgBlue.colorset/Contents.json
  NyamNyam/NyamNyam/Global/Pallete.swift
  NyamNyam/NyamNyam/Screens/Home/Components/OptionSelectModule/CafeteriaSelectViewComponents/CafeteriaButton.swift
  NyamNyam/NyamNyam/Screens/Home/Components/OptionSelectModule/CampusSelectView.swift
  NyamNyam/NyamNyam/Screens/Home/Components/OptionSelectModule/OptionSelectModuleViewController.swift
  NyamNyam/NyamNyam/Screens/Home/ContentCarouselModule/Components/CarouselCell.swift
  NyamNyam/NyamNyam/Screens/Home/ContentCarouselModule/Components/ExpandableMealCardView.swift
  NyamNyam/NyamNyam/Screens/Home/ContentCarouselModule/ContentCarouselModuleViewController.swift
  NyamNyam/NyamNyam/Screens/Home/HomeViewController.swift
Labels: feature

#34 식단 별 운영 시간 데이터를 추가하였습니다.
  NyamNyam/NyamNyam.xcodeproj/project.pbxproj
  NyamNyam/NyamNyam/Global/Extension+/String+.swift
  NyamNyam/NyamNyam/Global/Manager/DataManager.swift
  NyamNyam/NyamNyam/Global/Manager/DummyString.swift
  NyamNyam/NyamNyam/Network/Dummy.json
  NyamNyam/NyamNyam/Network/Model/Meal.swift
Labels: feature

#35 Default한 Content 영역을 만들었습니다.
  NyamNyam/NyamNyam.xcodeproj/project.pbxproj
  NyamNyam/NyamNyam/Global/Extension+/Date+.swift
  NyamNyam/NyamNyam/Global/Manager/DataManager.swift
  NyamNyam/NyamNyam/Network/Model/Campus.swift
  NyamNyam/NyamNyam/Network/Model/Meal.swift
  NyamNyam/NyamNyam/Network/Model/RunningStatus.swift
  NyamNyam/NyamNyam/Screens/Home/ContentCarouselModule/Components/CarouselCell.swift
  NyamNyam/NyamNyam/Screens/Home/ContentCarouselModule/Components/ContentStackView.swift
  NyamNyam/NyamNyam/Screens/Home/ContentCarouselModule/Components/ExpandableMealCardView.swift
  NyamNyam/NyamNyam/Screens/Home/ContentCarouselModule/ContentCarouselModuleViewController.swift
Labels: feature

#41 생활관B의 contentView를 업데이트하였습니다.
  NyamNyam/NyamNyam/Screens/Home/ContentCarouselModule/Components/ContentStackView.swift
Labels: feature

#40 SettingView의 두번째 섹션을 구현하였습니다
  NyamNyam/NyamNyam.xcodeproj/project.pbxproj
  NyamNyam/NyamNyam/Screens/Setting/Components/SettingListViewModule/Components/SettingListTableViewCell.swift
  NyamNyam/NyamNyam/Screens/Setting/Components/SettingListViewModule/Components/SettingWebViewController.swift
  NyamNyam/NyamNyam/Screens/Setting/Components/SettingListViewModule/SettingListTableViewController.swift
  NyamNyam/NyamNyam/Screens/Setting/SettingViewController.swift
Labels: feature

#44 학생식당 Content UI를 수정하였고 애니메이션을 개선하였습니다.
  NyamNyam/NyamNyam/Network/Dummy.json
  NyamNyam/NyamNyam/Screens/Home/ContentCarouselModule/Components/CarouselCell.swift
  NyamNyam/NyamNyam/Screens/Home/ContentCarouselModule/Components/ContentStackView.swift
Labels: feature, refactor

#49 카우버거와 라면의 ContentView UI를 업데이트 하였습니다.
  NyamNyam/NyamNyam/Global/Manager/DataManager.swift
  NyamNyam/NyamNyam/Network/Dummy.json
  NyamNyam/NyamNyam/Network/Model/Meal.swift
  NyamNyam/NyamNyam/Screens/Home/ContentCarouselModule/Components/CarouselCell.swift
  NyamNyam/NyamNyam/Screens/Home/ContentCarouselModule/Components/ContentStackView.swift
  NyamNyam/NyamNyam/Screens/Home/ContentCarouselModule/Components/ExpandableMealCardView.swift
  NyamNyam/NyamNyam/Screens/Home/ContentCarouselModule/ContentCarouselModuleViewController.swift
Labels: feature

#47 SettingView의 카페테리아 순서를 변경하는 섹션을 구현합니다
  NyamNyam/NyamNyam.xcodeproj/project.pbxproj
  NyamNyam/NyamNyam/Screens/Setting/Components/SetCafeteriaOrderModule/Components/SetCafeteriaOrderTableViewCell.swift
  NyamNyam/NyamNyam/Screens/Setting/Components/SetCafeteriaOrderModule/Components/SetCafeteriaOrderTitleView.swift
  NyamNyam/NyamNyam/Screens/Setting/Components/SetCafeteriaOrderModule/SetCafeteriaOrderTableViewController.swift
  NyamNyam/NyamNyam/Screens/Setting/SettingViewController.swift
Labels: feature

#54 카우버거,라멘의 Card와 time label을 생성하였고, 기타 UI를 수정하였습니다.
  NyamNyam/NyamNyam.xcodeproj/project.pbxproj
  NyamNyam/NyamNyam/Assets.xcassets/Colors/blueBackground.colorset/Contents.json
  NyamNyam/NyamNyam/Assets.xcassets/Colors/grayBackground.colorset/Contents.json
  NyamNyam/NyamNyam/Assets.xcassets/Colors/redBackground.colorset/Contents.json
  NyamNyam/NyamNyam/Assets.xcassets/Colors/yellowBackGround.colorset/Contents.json
  NyamNyam/NyamNyam/Global/Extension+/Date+.swift
  NyamNyam/NyamNyam/Global/Pallete.swift
  NyamNyam/NyamNyam/Network/Dummy.json
  NyamNyam/NyamNyam/Network/Model/Meal.swift
  NyamNyam/NyamNyam/Network/Model/RunningStatus.swift
  NyamNyam/NyamNyam/Screens/Home/ContentCarouselModule/Components/CarouselCell.swift
  NyamNyam/NyamNyam/Screens/Home/ContentCarouselModule/Components/ContentStackView.swift
  NyamNyam/NyamNyam/Screens/Home/ContentCarouselModule/Components/ExpandableMealCardView.swift
  NyamNyam/NyamNyam/Screens/Home/ContentCarouselModule/Components/TimeLabelView.swift
  NyamNyam/NyamNyam/Screens/Home/ContentCarouselModule/ContentCarouselModuleViewController.swift
Labels: feature, refactor

#37 FireStore와 연동 및 FBManager를 구현하여 json 파일을 로컬에서 읽고 쓰도록 하였습니다.
  .gitignore
  NyamNyam/NyamNyam.xcodeproj/project.pbxproj
  NyamNyam/NyamNyam.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  NyamNyam/NyamNyam/Application/AppDelegate.swift
  NyamNyam/NyamNyam/Global/Manager/DataManager.swift
  NyamNyam/NyamNyam/Global/Manager/JsonManager.swift
  NyamNyam/NyamNyam/Network/Firebase/FBManager.swift
Labels: feature

#51 캠퍼스 선택 섹션과 SettingViewController를 구현하였습니다
  NyamNyam/NyamNyam.xcodeproj/project.pbxproj
  NyamNyam/NyamNyam/Assets.xcassets/Colors/bgGray.colorset/Contents.json
  NyamNyam/NyamNyam/Global/Pallete.swift
  NyamNyam/NyamNyam/Screens/Setting/Components/BackButtonView.swift
  NyamNyam/NyamNyam/Screens/Setting/Components/SetCafeteriaOrderModule/SetCafeteriaOrderTableViewController.swift
  NyamNyam/NyamNyam/Screens/Setting/Components/SetDefaultCampusModule/SetDefaultCampusView.swift
  NyamNyam/NyamNyam/Screens/Setting/Components/SettingListViewModule/SettingListTableViewController.swift
  NyamNyam/NyamNyam/Screens/Setting/SettingViewController.swift
  NyamNyam/NyamNyam/Screens/Setting/SettingViewModel.swift
Labels: feature

#53 네트워크 검사 모듈을 추가합니다
  NyamNyam/NyamNyam.xcodeproj/project.pbxproj
  NyamNyam/NyamNyam/Application/AppDelegate.swift
  NyamNyam/NyamNyam/Application/SceneDelegate.swift
  NyamNyam/NyamNyam/Global/Extension+/Date+.swift
  NyamNyam/NyamNyam/Global/Extension+/UserDefaults+.swift
  NyamNyam/NyamNyam/Global/Reachability.swift
Labels: feature

#55 SettingView의 UI를 수정합니다
  NyamNyam/NyamNyam/Screens/Setting/Components/BackButtonView.swift
  NyamNyam/NyamNyam/Screens/Setting/Components/SetCafeteriaOrderModule/SetCafeteriaOrderTableViewController.swift
  NyamNyam/NyamNyam/Screens/Setting/Components/SettingListViewModule/Components/SettingWebViewController.swift
  NyamNyam/NyamNyam/Screens/Setting/SettingViewController.swift
Labels: refactor

#58 네트워크 미연결 시에 WebView의 Alert를 구현하였습니다
  NyamNyam/NyamNyam/Screens/Setting/Components/SettingListViewModule/Components/SettingWebViewController.swift
Labels: feature

#60 FireStore 로직의 선후관계를 조정하였습니다.
  NyamNyam/NyamNyam.xcodeproj/project.pbxproj
  NyamNyam/NyamNyam/Application/SceneDelegate.swift
  NyamNyam/NyamNyam/Network/Firebase/FBManager.swift
  NyamNyam/NyamNyam/Network/Firebase/GoogleService-Info.plist
Labels: fix

#61 데이터 최신화 검사로직을 수정합니다
  NyamNyam/NyamNyam/Application/SceneDelegate.swift
  NyamNyam/NyamNyam/Network/Firebase/FBManager.swift
Labels: fix

#64 HomeViewController와 SettingViewController를 연결합니다
  NyamNyam/NyamNyam/Assets.xcassets/Buttons/setting.imageset/Contents.json
  NyamNyam/NyamNyam/Assets.xcassets/Buttons/setting.imageset/icon-setting-mono 1.svg
  NyamNyam/NyamNyam/Assets.xcassets/Buttons/setting.imageset/icon-setting-mono 2.svg
  NyamNyam/NyamNyam/Assets.xcassets/Buttons/setting.imageset/icon-setting-mono.svg
  NyamNyam/NyamNyam/Screens/Home/HomeViewController.swift
Labels: feature

#68 AlertManager를 만들고 네트워크 오류에 대응하여 사용하였습니다.
  NyamNyam/NyamNyam.xcodeproj/project.pbxproj
  NyamNyam/NyamNyam/Application/SceneDelegate.swift
  NyamNyam/NyamNyam/Global/Manager/AlertManager.swift
  NyamNyam/NyamNyam/Screens/Home/HomeViewController.swift
Labels: feature

#69 Launch Screen을 구현하였습니다
  NyamNyam/NyamNyam/Application/AppDelegate.swift
  NyamNyam/NyamNyam/Application/Base.lproj/LaunchScreen.storyboard
  NyamNyam/NyamNyam/Assets.xcassets/AppIcon.appiconset/AppIcon1024x1024.png
  NyamNyam/NyamNyam/Assets.xcassets/AppIcon.appiconset/Contents.json
  NyamNyam/NyamNyam/Assets.xcassets/AppIcon.appiconset/Frame 2.png
  NyamNyam/NyamNyam/Assets.xcassets/LaunchScreen/Contents.json
  NyamNyam/NyamNyam/Assets.xcassets/LaunchScreen/launchImage.imageset/Contents.json
  NyamNyam/NyamNyam/Assets.xcassets/LaunchScreen/launchImage.imageset/LaunchImage 1.svg
  NyamNyam/NyamNyam/Assets.xcassets/LaunchScreen/launchImage.imageset/LaunchImage 2.svg
  NyamNyam/NyamNyam/Assets.xcassets/LaunchScreen/launchImage.imageset/LaunchImage.svg
Labels: feature

#71 앱 전체의 Font를 변경합니다
  NyamNyam/NyamNyam.xcodeproj/project.pbxproj
  NyamNyam/NyamNyam/Application/Base.lproj/LaunchScreen.storyboard
  NyamNyam/NyamNyam/Info.plist
  NyamNyam/NyamNyam/Screens/Home/Components/OptionSelectModule/CafeteriaSelectViewComponents/CafeteriaButton.swift
  NyamNyam/NyamNyam/Screens/Home/Components/OptionSelectModule/CampusSelectView.swift
  NyamNyam/NyamNyam/Screens/Home/Components/OptionSelectModule/DateSelectViewComponents/DateButton.swift
  NyamNyam/NyamNyam/Screens/Home/ContentCarouselModule/Components/CarouselCell.swift
  NyamNyam/NyamNyam/Screens/Home/ContentCarouselModule/Components/ContentStackView.swift
  NyamNyam/NyamNyam/Screens/Home/ContentCarouselModule/Components/ExpandableMealCardView.swift
  NyamNyam/NyamNyam/Screens/Home/ContentCarouselModule/Components/TimeLabelView.swift
  NyamNyam/NyamNyam/Screens/Setting/Components/BackButtonView.swift
  NyamNyam/NyamNyam/Screens/Setting/Components/SetCafeteriaOrderModule/Components/SetCafeteriaOrderTableViewCell.swift
  NyamNyam/NyamNyam/Screens/Setting/Components/SetCafeteriaOrderModule/Components/SetCafeteriaOrderTitleView.swift
  NyamNyam/NyamNyam/Screens/Setting/Components/SetDefaultCampusModule/SetDefaultCampusView.swift
  NyamNyam/NyamNyam/Screens/Setting/Components/SettingListViewModule/Components/SettingListTableViewCell.swift
Labels: refactor

#74 다운로드 동안 런치스크린이 뜨도록 했고, 설정창이 다크모드로 유지되도록 했습니다.
  NyamNyam/NyamNyam/Application/Base.lproj/LaunchScreen.storyboard
  NyamNyam/NyamNyam/Application/SceneDelegate.swift
  NyamNyam/NyamNyam/Screens/Setting/Components/SettingListViewModule/Components/SettingListTableViewCell.swift
  NyamNyam/NyamNyam/Screens/Setting/SettingViewController.swift
Labels: feature

#76 UserDefault를 검사하기 전에 잘못 set하는 부분을 삭제하였습니다.
  NyamNyam/NyamNyam.xcodeproj/project.pbxproj
  NyamNyam/NyamNyam/Application/AppDelegate.swift
  NyamNyam/NyamNyam/Application/SceneDelegate.swift
  NyamNyam/NyamNyam/Global/Extension+/UserDefaults+.swift
  NyamNyam/NyamNyam/Global/Font/Pretendard-Bold.otf
  NyamNyam/NyamNyam/Global/Font/Pretendard-Light.otf
  NyamNyam/NyamNyam/Global/Font/Pretendard-SemiBold.otf
Labels: fix

#80 Setting의 변경사항이 돌아갈 때 Home에 적용되도록 하였습니다.
  NyamNyam/NyamNyam/Screens/Home/Components/OptionSelectModule/OptionSelectModuleViewController.swift
  NyamNyam/NyamNyam/Screens/Home/HomeViewController.swift
  NyamNyam/NyamNyam/Screens/Home/HomeViewModel.swift
Labels: feature

#79 SettingView의 UI 수정 및 개인정보정책 URL을 변경하였습니다
  NyamNyam/NyamNyam/Assets.xcassets/Buttons/chevron.right.imageset/Contents.json
  NyamNyam/NyamNyam/Assets.xcassets/Buttons/chevron.right.imageset/arrow-right 1.svg
  NyamNyam/NyamNyam/Assets.xcassets/Buttons/chevron.right.imageset/arrow-right 2.svg
  NyamNyam/NyamNyam/Assets.xcassets/Buttons/chevron.right.imageset/arrow-right.svg
  NyamNyam/NyamNyam/Screens/Setting/Components/BackButtonView.swift
  NyamNyam/NyamNyam/Screens/Setting/Components/SetCafeteriaOrderModule/SetCafeteriaOrderTableViewController.swift
  NyamNyam/NyamNyam/Screens/Setting/Components/SettingListViewModule/SettingListTableViewController.swift
Labels: fix

#85 개인정보 링크를 수정하였습니다.
  NyamNyam/NyamNyam/Screens/Setting/Components/SettingListViewModule/SettingListTableViewController.swift
Labels: fix

#88 Date의 유효성을 검사하고, 이에 맞는 UI 처리를 하였습니다.
  NyamNyam/NyamNyam.xcodeproj/project.pbxproj
  NyamNyam/NyamNyam/Application/Base.lproj/LaunchScreen.storyboard
  NyamNyam/NyamNyam/Application/SceneDelegate.swift
  NyamNyam/NyamNyam/Assets.xcassets/Colors/invalidButton.colorset/Contents.json
  NyamNyam/NyamNyam/Assets.xcassets/smile.imageset/Contents.json
  NyamNyam/NyamNyam/Assets.xcassets/smile.imageset/smile.png
  NyamNyam/NyamNyam/Assets.xcassets/smile.imageset/smile@2x.png
  NyamNyam/NyamNyam/Assets.xcassets/smile.imageset/smile@3x.png
  NyamNyam/NyamNyam/Global/Pallete.swift
  NyamNyam/NyamNyam/Screens/Home/Components/OptionSelectModule/DateSelectView.swift
  NyamNyam/NyamNyam/Screens/Home/Components/OptionSelectModule/DateSelectViewComponents/DateButton.swift
  NyamNyam/NyamNyam/Screens/Home/Components/OptionSelectModule/OptionSelectModuleViewController.swift
  NyamNyam/NyamNyam/Screens/Setting/Components/SettingListViewModule/SettingListTableViewController.swift
  NyamNyam/NyamNyam/Screens/Toast/ToastView.swift
Labels: feature
